package com.xdrapor.safeguard.utilities;

public enum SGCheckTag {
	
	MOVEMENT_SPEED,
	MOVEMENT_HORIZONTAL,
	MOVEMENT_VERTICAL,
	MOVEMENT_DISTANCE,
	MOVEMENT_INVALID,
	MOVEMENT_MOREPACKETS,
	MOVEMENT_FALL,
	
	BLOCK_REACH,
	BLOCK_BREAKFREQUENCY,
	BLOCK_BREAKSPEED,
	BLOCK_PLACESPEED,
	
	COMBAT_SPEED,
	COMBAT_REACH,
}
